# -*- coding: utf-8 -*-
"""JUEGO DEL AHORCADO JOSE DANIEL AYALA BARRERA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XnKXMjHJDBjHnXXNyYwfpYTfBcV5rfKM

<div class="markdown-google-sans">
  <h2>JUEGO DEL AHORCADO</h2>
</div>

*   José Daniel Ayala Barrera
*   Talento Tech
*   Inteligencia Artificial
*   Módulo Básico
*   Abril 2024
"""

# Importamos librerías
import random

#aqui se almacenaran los valores del arreglo
palabras = ['gato', 'perro', 'elefante', 'jirafa', 'rinoceronte', 'leon']

# Creamos variables del juego

palabra_secreta = random.choice(palabras) # elección aleatoria de palabra secreta
palabra_oculta = "_" * len(palabra_secreta)

intentos = 0 # inicializamos contador
letras_adivinadas = []

while intentos < 6: # Definimos en 6 el número de intentos

    letra = input("Ingrese una letra, por favor: ")
    if letra in letras_adivinadas:
        print("Ya adivinó esa letra, Intente nuevamente!!!")
    elif letra in palabra_secreta:
        for i in range(len(palabra_secreta)):
            if palabra_secreta[i] == letra:
                palabra_oculta = palabra_oculta[:i] + letra + palabra_oculta[i+1:]
        print("Excelente!!! La palabra es:", palabra_oculta)
        if "_" not in palabra_oculta:
            print("Felicitaciones, ha ganado!!!")
            break
    else:
        intentos += 1
        print("Letra incorrecta, quedan", 6-intentos, "intentos.")
        letras_adivinadas.append(letra)
        if intentos == 1:
            print("  O")
        elif intentos == 2:
            print("  O")
            print("  |")
        elif intentos == 3:
            print("  O")
            print(" /|")
        elif intentos == 4:
            print("  O")
            print(" /|\\")
        elif intentos == 5:
            print("  O")
            print(" /|\\")
            print(" /")
        elif intentos == 6:
            print("  O")
            print(" /|\\")
            print(" / \\")
            print("Lo siento, ha perdido!!!. La palabra secreta era", palabra_secreta)
            break